# Generated by Django 2.1 on 2018-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(default='', max_length=200, verbose_name='Название препарата')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('contraindications_text', models.CharField(default='', max_length=2000, verbose_name='Есть ли у вас (противопоказания)')),
                ('precautions_text', models.CharField(default='', max_length=2000, verbose_name='Есть ли у вас (предостережения)')),
                ('drug_guide_url', models.URLField(verbose_name='Ссылка на препарат')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order_id', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('question_text', models.CharField(default='', max_length=100, verbose_name='Текст вопроса')),
                ('diagnosis_text', models.CharField(default='', max_length=2000, verbose_name='Диагноз')),
                ('recommendations_text', models.CharField(default='', max_length=2000, verbose_name='Рекомендации')),
                ('interrupt_boolean', models.BooleanField(default=False)),
                ('drugs', models.ManyToManyField(to='headache.Drug')),
            ],
        ),
    ]
